### PR TITLE
Modernize chart

### PR DESCRIPTION
**Pull request by ryzokuken**
@rajgoel check this out! Let me know what you think...

### CODE REVIEW

**Comment by ryzokuken** [comment]
BTW, I just noticed that this is pretty much exactly how the `menu` package is set up anyway, so not something too flashy for sure...

**Comment by rajgoel** [comment]
With this PR, chart.js is a dependency and no longer included. Thus, the old-school way of simply downloading the plugin and copying the files to the server will no longer work, right?

**Comment by ryzokuken** [comment]
Yes, but the tradeoff means that it is easier to upgrade to a new version of Chart.js (the current version was left as-is but someone should look into it, the current version is quite old).

**Comment by ryzokuken** [comment]
Also, ideally you would just `npm install reveal-plugin-chart` or something similar and you could `import RevealChart from 'reveal-plugin-chart'` without any manual intervention. Things are still copied/downloaded, but not manually.

**Comment by rajgoel** [comment]
Hi, 
I just played around a little. It appears that when using 

```js
const RevealChart = {
    id: 'RevealChart',
    init: function(deck) {
        initChart(deck);
    },
    update: function(canvas, idx, data) { update(canvas, idx, data); },
};

export default RevealChart;
```

I cannot use older presentations without changes. Moreover, it is unclear to me how to update presentations.

**Comment by ryzokuken** [comment]
> I cannot use older presentations without changes. 

Yes. That's a side effect. We could support both for backwards compatibility, but I made it a `2.0.0` release on purpose so that we don't need to continue to pollute the `window` namespace for backwards compat.

> Moreover, it is unclear to me how to update presentations.

Since we no longer set `RevealChart` on the `window` namespace but instead export it as a module, anytime you want to use it, you need to import it by `import RevealChart from 'reveal-plugin-chart';`. Rest everything should work the same.

**Comment by rajgoel** [comment]
Sorry, this is still not clear to me. If I add 
```html
<script>
import RevealChart from "../reveal.js-plugins/chart/plugin.js"
</script>
```
I get an error `Uncaught SyntaxError: import declarations may only appear at top level of a module`

What am I doing wrong?

**Comment by rajgoel** [comment]
Ok, I guess I have to use it this way:

```html
<script type="module">
import RevealChart from "../reveal.js-plugins/chart/plugin.js"

Reveal.initialize({
// ..
});
</script>
```

but now I get `TypeError: this is undefined` for 
```js
this.update = updateChart;
```

**Comment by ryzokuken** [comment]
> Ok, I guess I have to use it this way:

Right, sorry, if you are not using a bundler like `webpack` and using `script` tags directly, you should use `<script type="module">`.

Regarding the `TypeError: this is undefined` error, I'm not quite sure what's wrong... Maybe converting `initChart` to the new class/constructor syntax would fix it?

**Comment by ryzokuken** [comment]
> I agree that Chart.min.js can be removed from the plugin and loaded e.g. via CDN. This will remove overhead when newer Chart.js versions come out.

Yes and no. Yes that the dependency should come from elsewhere, not have the files copied manually, but asking users to include it from a CDN manually would hurt if there is ever a new release of Chart.js that doesn't work with the version of plugin available at that time. Instead, you should clearly mention which version of Chart.js to use in the `package.json` and `npm install` would pick it up automatically.

**Comment by rajgoel** [comment]
> but asking users to include it from a CDN manually would hurt if there is ever a new release of Chart.js that doesn't work with the version of plugin available at that time.

Well, the version number can be fixed with the  CDN:
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.2.0/chart.min.js"></script>
```
Shouldn't this be enough?

> ` npm install` would pick it up automatically.

While npm is good for developers, it really can be an entry barrier to users who have no experience with it and just want to upload their presentation on a web-server. Thus relying exclusively on npm is not an option for the plugins.

P.S. Thanks a lot for your ongoing feedback :smile:

**Comment by ryzokuken** [comment]
> Shouldn't this be enough?

Right, I didn't realize this was a thing. I still prefer using `npm` and bundlers, but don't mind this :smile: 

Perhaps we could allow either? Something like:

```javascript
if (!window.Chart) {
  window.Chart = import('chart.js');
} 
```

maybe?

> While npm is good for developers, it really can be an entry barrier to users who have no experience with it and just want to upload their presentation on a web-server. Thus relying exclusively on npm is not an option for the plugins.

I understand. I suppose I was a little biased. Perhaps the solution I mentioned above would kill both birds with a single stone?

> P.S. Thanks a lot for your ongoing feedback smile

You're welcome! Thanks for being super open-minded about this :smile:

**Comment by ryzokuken** [comment]
By the way, I just recalled that ES Modules `imports` work great with static URLs and would replicate the behavior you would expect with a CDN `script` tag so you could also do:

```javascript
import Chart from 'https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.2.0/chart.min.js';
```

**Comment by t-fritsch** [comment]
Hi, 

first of all : thanks **a lot** for the great work on this plugin ! I've been using it some years ago and was really happy with it at that time.
Now I'm back on reveal for some projects and I was just looking for ESM support for this plugin and just stumbled upon this PR that seemed quite promising.

I wonder if it has been closed without being merged because there are no plans to support ESM or if it is because there is another migration plan ongoing ?

I too think that modules are quite the way for modern JS since a couple of years now, for example all the others reveal plugin I use in my new reveal presentations support ESM and allow to use Reveal through npm as mentioned in https://revealjs.com/installation/#installing-from-npm, I think it would be really great if chart plugin could support this too ! 😍

**Pull request closed without merging**
