### PR TITLE
Audio speed

### PR DESCRIPTION
**Pull request by lechten**
This MR introduces the new option `defaultAudioRate` to control the speed of audio playback.

### CODE REVIEW

**Comment by lechten** [comment]
Why do you [include](https://github.com/rajgoel/reveal.js-plugins/blob/master/audio-slideshow/plugin.js#L407) the call `nextAudio.load()`? 

I do not need it, and it resets the audio element's properties, including the speed. Per [W3 school](https://www.w3schools.com/tags/av_met_load.asp), it re-loads the element, while you seem to aim for a pre-load...

**Comment by lechten** [comment]
@rajgoel What do you think about an option to control the speed of audio? My students like that...

**Comment by rajgoel** [comment]
@lechten: I think this could be a really nice enhancement (and sorry for letting you wait with this PR for so long). One of the reasons, that I am hesitant about this are the side effects of video-playback linked to the audio controls and to playback of recorded chalkboard drawings. Also the animate plugin somehow requires the correct playback timing. Do you have an idea on how to deal with these side effects? Alternatively, some mechanism would be needed to prevent using the feature in such use cases.

**Comment by rajgoel** [comment]
One idea could be to disable the feature when `RevealChalkboard` or `RevealAnimate` are loaded (or at least to print a warning to console). 

 I'll be happy to merge if
 - video playback attached to the audio controls as shown [here](https://rajgoel.github.io/reveal.js-demos/#1/3/?topic=audio-slideshow) also works (by copying the playback rate)
 - the potential conflicts with other plugins are reasonable documented,
 - there is a method to `RevealAudioSlideshow.getPlaybackRate()`  or similar that can be used to get the current playback rate.

Can you please also check whether the PR still works with the current version (it looks like it should, but i haven't tested).

**Comment by rajgoel** [comment]
Btw. is the playback rate copied or rest to 1 when jumping from on slide to another?

**Comment by lechten** [comment]
> (by copying the playback rate)

I am not sure what to copy where. So far, I initialize each audio with `defaultAudioRate`. Also, in `selectAudio` I copy the previous audio rate (similarly to what exists for volume and muted).

>  the potential conflicts with other plugins are reasonable documented,

What about this:
Note that this option changes the speed of *all* audios, which may interfere with other plugins such as `RevealChalkboard` or `RevealAnimate`, which may have their own notion of the "correct" playback rate.
 
> there is a method to `RevealAudioSlideshow.getPlaybackRate()`  or similar that can be used to get the current playback rate.

Should this return `defaultAudioRate` or the rate of `currentAudio` (if set) or something else?

> Can you please also check whether the PR still works with the current version (it looks like it should, but i haven't tested).

Yes, it does.

> Btw. is the playback rate copied or reset to 1 when jumping from on slide to another?

It is reset to 1 by `nextAudio.load()` in the `play` event listener, which I suggest to remove (see [above](https://github.com/rajgoel/reveal.js-plugins/pull/148#issuecomment-1464891048)). If I pause an audio in your demo and advance to the next slide, it starts with the rate set to 1 (as `selectAudio` is not called, which would undo the resetting to 1).

**Comment by rajgoel** [comment]
> > (by copying the playback rate)

> I am not sure what to copy where. So far, I initialize each audio with defaultAudioRate. Also, in selectAudio I copy the previous audio rate (similarly to what exists for volume and muted).

Each media element on the current slide or fragment with  `data-audio-controls`  is [synchronised with the audio playback](https://github.com/rajgoel/reveal.js-plugins/tree/master/audio-slideshow#linking-audio-controls-to-embedded-video). Thus, the playback rates need to be the same.

> >   there is a method to RevealAudioSlideshow.getPlaybackRate() or similar that can be used to get the current playback rate.

> Should this return defaultAudioRate or the rate of currentAudio (if set) or something else?

This function should return the playback radio currently used (so that it could be picked up by the other plugins to synchronize).


> >    Btw. is the playback rate copied or reset to 1 when jumping from on slide to another?

> It is reset to 1 by `nextAudio.load()` in the play event listener, which I suggest to remove (see https://github.com/rajgoel/reveal.js-plugins/pull/148#issuecomment-1464891048). If I pause an audio in your demo and advance to the next slide, it starts with the rate set to 1 (as selectAudio is not called, which would undo the resetting to 1).

I guess `nextAudio.load()` can be removed, because I indeed believed it would preload not reload. The important thing for me is that for both explicit slide changes and when auto-advancing to the next slide or fragment, the playback rate of  media elements with `data-audio-controls`  need to be (un)set appropriately.

**Comment by lechten** [comment]
I rebased the branch on top of master (4.2.3).

I renamed the variable from `audio` to `playback`, as video is affected as well and introduced another variable to keep track of the current rate with event handlers.

Note that I no longer set the speed in `selectAudio()` but upon `play`.  This also works if users pause one audio and navigate elsewhere (and if not every slide contains audio).  A similar approach might be more robust for `volume` and `muted` as well.  Is that worth the effort (adding variables with event handlers)?

As discussed, I removed the call `nextAudio.load()` (and code leading to it).  In `setupAudioElement()`, you set attribute `preload` to `none`.  Maybe this could be `auto`?

**Comment by rajgoel** [comment]
Thanks a lot for the PR. Please let me know should there be any remaining issues with this.

**Comment by lechten** [comment]
Thanks for merging :smile:

**Comment by TS-CUBED** [comment]
Just to confirm: there is currently no way to have the playback speed synchronise with chalkboard annotation?

**Comment by rajgoel** [comment]
As far as I remember, the chalkboard replay currently does not support different playback rates.

**Pull request merged**
