### PR TITLE
Updated chart plugin to work with Reveal 4.0.0

### PR DESCRIPTION
**Pull request by kotborealis**
Solves #81 

[Created demo for testing, based on rajgoel/reveal.js-demos](https://github.com/kotborealis/revealjs-charts-demo), [also published on gh-pages](https://kotborealis.github.io/revealjs-charts-demo/index.html#/).

### CODE REVIEW

**Comment by rajgoel** [comment]
:clap:  Thanks a lot! I will include this when I update all plugins to reveal v4.

**Comment by kotborealis** [comment]
It shouldn't be that hard, you'll only need to updated plugin initialization and demos.

I'll try to update other plugins in my free time.

**Comment by rajgoel** [comment]
Great! Thanks for the info, I haven't found time yet to look at the API changes (terribly busy currently)

**Comment by its-thomas** [comment]
Thanks so much for putting in the work!

I have just tested your demo with the following browsers on my latest debian 10 stable:

- Firefox ESR (Version 68.10.0)
- Opera (Version 69.0.3686.57)

Everything seems to be displayed correctly, except "STACKED BAR CHART FROM CSV FILE WITH JSON CONFIGURATION" which is not displayed at all in neither browser.

**Comment by kotborealis** [comment]
@its-thomas thanks for testing!

I'd just like to clarify that CSV files won't work without http server due to CORS policy:



It's not an issue with how plugin works and can't be fixed.

**Comment by its-thomas** [comment]
@kotborealis, you wrote:

> It shouldn't be that hard, you'll only need to updated plugin initialization and demos.

Does that mean I just have to copy & paste certain lines from the new index.html into my .html file in order to get it to work with Reveal 4.0.0?

**Comment by kotborealis** [comment]
[You need to update the plugin](https://github.com/rajgoel/reveal.js-plugins/pull/82/files#diff-aebc635d4a885e35926b7816f3f1ae90R18) and [`index.html`](https://github.com/rajgoel/reveal.js-plugins/pull/82/files#diff-9630b72b68249efe68cdf0b1a2f74e08R13)

**Comment by its-thomas** [comment]
I have just successfully created – or at least, duplicated ;-) – the "Line chart from JSON string" example in my own reveal.js presentation (version 4.0.2)

Thanks a lot!

**Comment by rajgoel** [comment]
@kotborealis Thanks again for your contribution. It helped a lot in figuring out how to update the other plugins.

**Pull request merged**
