### PR TITLE
Add instructions to use npm as an alternative to bower

### PR DESCRIPTION
**Pull request by pfisterer**
Hello @rajgoel, 
Thanks for the work on this plugin. I would love to use it via npm and I've seen that you've created [an npm package](https://www.npmjs.com/package/reveal.js-plugins). 

Could you maybe update this package to the latest version and include the updated instructions in this PR?

Best,
Dennis

### CODE REVIEW

**Comment by rajgoel** [comment]
> Could you maybe update this package to the latest version and include the updated instructions in this PR?

Unfortunatley, I am a total noob regarding npm :-) Could you kindly give me instructions how to update the npm package? 

Btw. I am currently testing and bugfixing the latest changes and will wait with the package update until I am confident that the recent changes to the plugins work.

**Comment by pfisterer** [comment]
:-) I'm not that experienced, too. 

I've followed [these](https://docs.npmjs.com/creating-and-publishing-unscoped-public-packages) instructions to [publish some of the stuff](https://github.com/pfisterer/reveal-template) that I reuse across several presentations.

Basically, I update the version number in `package.json` and then run `npm publish --access public`. I currently don't use any code bundler or the like. So I basically just publish the contents of my repository as is. I guess this would work for you, too.

**Comment by rajgoel** [comment]
Thanks, I'll try this as soon as I finished the current round of testing and bugfixing.

**Comment by pfisterer** [comment]
Great, thanks a million!

**Comment by matthewturk** [comment]
Would this make it likely to get picked up by CDNs, like jsdelivr or cdnjs?  That would be a huge win, too!

**Comment by pfisterer** [comment]
@matthewturk Packages published on npm are available at unpkg.com. E.g., version 1.0.0 of reveal.js-plugins is available at [https://unpkg.com/browse/reveal.js-plugins@1.0.0/](https://unpkg.com/browse/reveal.js-plugins@1.0.0/).

However, the version published via npm is rather outdated (last publish was 2 years ago).

@rajgoel Could you maybe publish the current version on npm, please?

@rajgoel I could also provide a PR with documentation on how to use your plugins via unpg.com or I can update the existing PR regarding the use of npm (cf. https://github.com/rajgoel/reveal.js-plugins/pull/96/files).

**Comment by rajgoel** [comment]
The updated version is now published at https://www.npmjs.com/package/reveal.js-plugins/v/4.1.2

**Pull request merged**
