### PR TITLE
I23 multiple colors

### PR DESCRIPTION
**Pull request by rinnert**
This implements the multi color feature requested in issue #23. 

By default, the chalk now has five colors and the marker has six. For the chalk, cursor images for the default colors are included. Colors and and cursor images are freely configurable. In particular users can provide as many colors as they like for the slide canvas and the board. The suggested key bindings will bind 'color forward' to 'f' and 'color backward' to 'g'.

I have also added a few more customization options, they are documented in the README.md.

The default behaviour is unchanged. All old user configurations will work exactly as before.

### CODE REVIEW

**Comment by rajgoel** [comment]
@rInnert Kurt, thanks a lot for the PR! I will review it asap.
:clap:

**Comment by rajgoel** [comment]
Again many thanks for your contribution! Your PR is now merged. Just did some very minor edits, in particular, the recommended keys to  switch colors ('f' was already taken for full screen).

**Comment by bcouetil** [comment]
@rinnert thank you very much for your contribution, this works very well and adds everything I dreamed about this plugin (with width configuration, etc.).

You rock :smile:

**Comment by rajgoel** [comment]
Please note that I changed the pen configuration and added a few colors in the last commit. To streamline the repository I removed the small cursors. I hope this is not a problem, you can easily add them by defining custom boardmarkers, chalks, and eraser.

**Comment by bcouetil** [comment]
Thank you, I tested after your changes, and everything seems perfect to me :heart:

**Pull request merged**
